import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
import path from 'path';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer, {
  cors: {
    origin: "*",
    methods: ["GET", "POST"]
  }
});

app.use(cors());
app.use(express.json());

// Serve static files from public directory
const publicPath = path.join(__dirname, '../../public');
app.use(express.static(publicPath));

// Mock Generator Logic
const mockGenerateApp = async (socket: any, spec: string) => {
  socket.emit('progress', 'Analyzing specifications...');
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  socket.emit('progress', 'Initializing Next.js 15 project...');
  await new Promise(resolve => setTimeout(resolve, 1500));

  socket.emit('progress', 'Configuring Tailwind CSS...');
  await new Promise(resolve => setTimeout(resolve, 1000));

  socket.emit('progress', 'Generating application code...');
  await new Promise(resolve => setTimeout(resolve, 2000));

  const generatedFiles = {
    'package.json': JSON.stringify({
      name: "generated-app",
      version: "0.1.0",
      private: true,
      scripts: {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint"
      },
      dependencies: {
        "react": "^19.0.0",
        "react-dom": "^19.0.0",
        "next": "15.0.0"
      },
      devDependencies: {
        "typescript": "^5",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        "postcss": "^8",
        "tailwindcss": "^3.4.1"
      }
    }, null, 2),
    'app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
          Generated App based on: ${spec}
        </p>
      </div>
    </main>
  );
}`,
    'app/layout.tsx': `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by Agent Battalion",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`,
    'tailwind.config.ts': `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;`,
    'next.config.js': `/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;`
  };

  socket.emit('progress', 'Done!');
  socket.emit('complete', generatedFiles);
};

io.on('connection', (socket) => {
  console.log('Client connected');

  socket.on('generate-app', async (spec: string) => {
    console.log('Received generation request:', spec);
    try {
      await mockGenerateApp(socket, spec);
    } catch (error) {
      console.error('Generation error:', error);
      socket.emit('error', 'Failed to generate app');
    }
  });

  socket.on('disconnect', () => {
    console.log('Client disconnected');
  });
});

const PORT = process.env.PORT || 4000;

httpServer.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
  console.log(`Serving static files from ${publicPath}`);
});
