import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer, {
  cors: {
    origin: "*",
    methods: ["GET", "POST"]
  }
});

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../../public')));

// Serve index.html for root route
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../../public/index.html'));
});

// Mock generator function
function generateNextJSApp(specification: string): { files: Record<string, string> } {
  const appName = specification.split(' ')[0] || 'my-app';
  
  return {
    files: {
      'package.json': JSON.stringify({
        name: appName.toLowerCase().replace(/\s+/g, '-'),
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint'
        },
        dependencies: {
          'next': '15.0.0',
          'react': '^19.0.0',
          'react-dom': '^19.0.0'
        },
        devDependencies: {
          '@types/node': '^20',
          '@types/react': '^19',
          '@types/react-dom': '^19',
          'typescript': '^5',
          'tailwindcss': '^3.4.0',
          'postcss': '^8',
          'autoprefixer': '^10.4.16',
          'eslint': '^8',
          'eslint-config-next': '15.0.0'
        }
      }, null, 2),
      'app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm">
        <h1 className="text-4xl font-bold mb-8 text-center">
          Welcome to ${appName}
        </h1>
        <p className="text-center text-gray-600 dark:text-gray-400">
          Generated by Agent Battalion
        </p>
      </div>
    </main>
  );
}`,
      'app/layout.tsx': `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${appName}',
  description: 'Generated by Agent Battalion',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
      'app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`,
      'tailwind.config.ts': `import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
export default config;`,
      'postcss.config.js': `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,
      'next.config.js': `/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;`,
      'tsconfig.json': JSON.stringify({
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [
            {
              name: 'next'
            }
          ],
          paths: {
            '@/*': ['./*']
          }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
      }, null, 2),
      '.gitignore': `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts`
    }
  };
}

// WebSocket connection handling
io.on('connection', (socket) => {
  console.log('Client connected:', socket.id);

  socket.on('generate-app', async (data: { specification: string }) => {
    const { specification } = data;
    
    // Emit progress updates
    socket.emit('progress', { message: 'Analyzing requirements...', progress: 10 });
    await new Promise(resolve => setTimeout(resolve, 500));
    
    socket.emit('progress', { message: 'Planning application structure...', progress: 30 });
    await new Promise(resolve => setTimeout(resolve, 500));
    
    socket.emit('progress', { message: 'Generating Next.js files...', progress: 50 });
    await new Promise(resolve => setTimeout(resolve, 500));
    
    socket.emit('progress', { message: 'Creating configuration files...', progress: 70 });
    await new Promise(resolve => setTimeout(resolve, 500));
    
    socket.emit('progress', { message: 'Finalizing...', progress: 90 });
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Generate the app
    const generatedApp = generateNextJSApp(specification);
    
    socket.emit('complete', {
      files: generatedApp.files,
      message: 'App generated successfully!'
    });
  });

  socket.on('disconnect', () => {
    console.log('Client disconnected:', socket.id);
  });
});

// REST endpoint for app generation (optional)
app.post('/api/generate', (req, res) => {
  const { specification } = req.body;
  
  if (!specification) {
    return res.status(400).json({ error: 'Specification is required' });
  }
  
  const generatedApp = generateNextJSApp(specification);
  res.json(generatedApp);
});

const PORT = process.env.PORT || 4000;
httpServer.listen(PORT, () => {
  console.log(`🚀 Agent Battalion server running on http://localhost:${PORT}`);
});
